### ISSUE TITLE
Filter Panel Module

### ISSUE THREAD

**Issue by pawelru** [openpharma/rinpharma_workshop_2021#37]
As a application user
In order to make subpopulation analysis
I want to apply filter and use filtered dataset accross the app modules

Implementation guide:
- Create a module (both server and ui part) - modify `shiny/filter.R` script.
  - UI part
    - add multiple widgets with all levels / range for a given dataset variable.
    - for ADSL: filter on SEX (multichoices radio-button), RACE (same as previously) and AGE (slider).
    - for ADAE: filter on AETERM and ASEQ (both multichoices radio-button)
    - for ADVS: filter on PARAMCD and AVISIT (both multichoices radio-button)
  - server part:
    - apply `dplyr::filter` with choices / range from input for each datasets
    - return a named list with reactive objects containing filtered dataset
    - introduce dependency between datasets so that filtering on demographics variables in ADSL would influence ADAE filitered dataset:
    ```
    ADSL_FILTERED <- dplyr::filter(ADSL, ...)
    ADSL_FILTERED_FINAL <- ADSL_FILTERED
    ADAE_FILTERED <- dplyr::filter(ADAE, ...)
    ADAE_FILTERED_FINAL <- dplyr::inner_join(ADSL_FILTERED, ADAE_FILTERED, ...)
    ADVS_FILTERED <- dplyr::filter(ADVS, ...)
    ADVS_FILTERED_FINAL <- dplyr::inner_join(ADSL_FILTERED, ADVS_FILTERED, ...)
    (return XYZ_FILTERED_FINAL datasets)
    ```
- Note that some logic would be repeated for multiple datasets - using modules could be a good idea to keep the code DRY.

**Comment by anhtr** [comment]
https://meet.jit.si/roomshiny
