### ISSUE TITLE
Data Previewer Module

### ISSUE THREAD

**Issue by pawelru** [openpharma/rinpharma_workshop_2021#38]
As an app user
In order to start my analysis
I want to see the loaded datasets.

Implementation guide:
- Create a module (both server and ui part) - modify `shiny/m_preview.R` script.
- Use `sidebarLayout` as in home module.
- Use `DT` package to render out the table.
- In the encodings panel please create a select input to choose the dataset

BONUS:
- Add a checkbox to see un-filtered data.

**Comment by LucaFoppoli** [comment]
https://meet.jit.si/datapreviewermodule
